import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:islam/ui/Quran/surah_name_widget.dart';

class QuranTab extends StatelessWidget {
  List<String> quranFehres = [
    "al-faatiHah | الفاتحه",
    "al-baqarah | البقرة",
    "aali-`imraan | آل عمران",
    "an-nisaa' | النساء",
    "al-maa'idah | المائدة",
    "al-an`aam | الأنعام",
    "al-a`raaf | الأعراف",
    "al-anfaal | الأنفال",
    "at-tawbah | التوبة",
    "yoonus | يونس",
    "hood | هود",
    "yoosuf | يوسف",
    "ar-Ra`d | الرعد",
    "ibraheem | إبراهيم",
    "al-Hijr | الحجر",
    "an-naHl | النحل",
    "al-Isra' | الإسراء",
    "al-kahf | الكهف",
    "maryam | مريم",
    "Taa haa | طه",
    "al-anbiyaa' | الأنبياء",
    "al-Hajj | الحج",
    "al-mu'minoon | المؤمنون",
    "an-noor | النّور",
    "al-furqaan | الفرقان",
    "ash-shu`araa' | الشعراء",
    "an-naml | النّمل",
    "al-qasas | القصص",
    "al-`ankaboot | العنكبوت",
    "ar-room | الرّوم",
    "luqmaan | لقمان",
    "as-sajdah | السجدة",
    "al-aHzab | الأحزاب",
    "as-Saba' | سبأ",
    "faaTir | فاطر",
    "yaa seen | يس",
    "aS-Saaffaat | الصافات",
    "Saad | ص",
    "az-zumar | الزمر",
    "Ghafir | غافر",
    "Fussilat | فصّلت",
    "ash-shooraa | الشورى",
    "azl-zukhruf | الزخرف",
    "ad-dukhaan | الدّخان",
    "al-jaathiyah | الجاثية",
    "al-aHqaaf | الأحقاف",
    "muHammad | محمد",
    "al-fatH | الفتح",
    "al-Hujuraat | الحجرات",
    "qaaf | ق",
    "ad-dhaariyaat | الذاريات",
    "aT-Toor | الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
            flex: 1,
            child: Image.asset('assets/images/qur2an_screen_logo.png')),
        Container(
          color: Theme.of(context).primaryColor,
          width: double.infinity,
          height: 1,
          margin: EdgeInsets.only(bottom: 4),
        ),
        Text(
          AppLocalizations.of(context)!.chapter_name,
          style: Theme.of(context).textTheme.displaySmall,
        ),
        Container(
          color: Theme.of(context).primaryColor,
          width: double.infinity,
          height: 1,
          margin: EdgeInsets.only(top: 4),
        ),
        Expanded(
            flex: 3,
            child: ListView.separated(
                itemBuilder: (buildContext, index) {
                  return SurahNameWidget(quranFehres[index], index);
                },
                itemCount: quranFehres.length,
                separatorBuilder: (buildContext, index) {
                  return Container(
                    color: Theme.of(context).hintColor,
                    width: double.infinity,
                    height: 1,
                    margin: EdgeInsets.symmetric(horizontal: 24),
                  );
                }))
      ],
    );
  }
}
